package com.travel.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2018.06.11 at 11:20:56 PM CEST 
//




import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType&gt;
*   &lt;complexContent&gt;
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
*       &lt;sequence&gt;
*         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
*         &lt;element name="servicename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
*         &lt;element ref="{http://www.travel.com/accommodation}Accommodation"/&gt;
*       &lt;/sequence&gt;
*     &lt;/restriction&gt;
*   &lt;/complexContent&gt;
* &lt;/complexType&gt;
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "id",
 "servicename",
 "accommodation"
})
@XmlRootElement(name = "AdditionalServices")

@Entity
public class AdditionalServices {

 @XmlElement(name = "Id")
 @Id
 @GeneratedValue(strategy=GenerationType.IDENTITY)
 protected long id;
 @XmlElement(required = true)
 protected String servicename;
 

 @ManyToOne
 @JoinColumn(name = "accommodation_id")
 @XmlElement(name = "Accommodation")
 protected Accommodation accommodation;

 /**
  * Gets the value of the id property.
  * 
  */
 public long getId() {
     return id;
 }

 /**
  * Sets the value of the id property.
  * 
  */
 public void setId(long value) {
     this.id = value;
 }

 /**
  * Gets the value of the servicename property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getServicename() {
     return servicename;
 }

 /**
  * Sets the value of the servicename property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setServicename(String value) {
     this.servicename = value;
 }

 /**
  * Gets the value of the accommodation property.
  * 
  * @return
  *     possible object is
  *     {@link Accommodation }
  *     
  */
 public Accommodation getAccommodation() {
     return accommodation;
 }

 /**
  * Sets the value of the accommodation property.
  * 
  * @param value
  *     allowed object is
  *     {@link Accommodation }
  *     
  */
 public void setAccommodation(Accommodation value) {
     this.accommodation = value;
 }

}